### ISSUE TITLE
Python 2 is gone, so it no longer works on Apple

### ISSUE THREAD

**Issue by timmyreal** [bbolli/tumblr-utils#234] opened 2022-04-30 22:10 UTC
As I understand, a recent update has removed Python 2 from Apple. If I use tumblr_backup.py, it returns "zsh: command not found: python". I tried using 2to3, but it doesn't seem to be changing much of anything in the file (for example, "httplib" doesnt get swapped out with "http.client"). Reinstalling Python 2 seems to be an extremely big hassle and it's apparently at the end of its life anyway. Is there any easy way to convert this program to Python3?

**Comment by Cebtenzzre** [comment] 2022-04-30 23:31
Check out [my fork](https://github.com/cebtenzzre/tumblr-utils.git), it's Python 3 compatible.

**Comment by Cebtenzzre** [comment] 2022-04-30 23:32
Closing as duplicate of #87.

**Closed by Cebtenzzre** 2022-04-30 23:32 UTC
