### ISSUE TITLE
Error in downloading

### ISSUE THREAD

**Issue by TheSimpleMango** [bbolli/tumblr-utils#177] opened 2018-12-13 10:36 UTC
The program stops after ~2000 posts, am I doing something wrong?
[terminal saved output.txt](https://github.com/bbolli/tumblr-utils/files/2675582/terminal.saved.output.txt)

**Comment by TiredToast** [comment] 2018-12-13 10:45
I'm having the same issue at around 3550; I believe "TypeError: cannot concatenate 'str' and 'NoneType' objects" was the last thing that I saw before everything stalled out. I've tried it on both Windows and Mac computers, and they both stall out there

**Comment by Cebtenzzre** [comment] 2018-12-13 17:37
Probably a duplicate of #167

**Closed** 2020-08-31 01:32 UTC
