### ISSUE TITLE
Installing youtube_dl on Windows 10

### ISSUE THREAD

**Issue by AmbiguousWeasle** [bbolli/tumblr-utils#175] opened 2018-12-13 02:48 UTC
Hello, I'm new Python and coding in general and so I'm sorry for asking possibly a simple question, but in reference to issue #89 I'm having trouble understanding the solution:

> Well, either try to install youtube-dl via pip, i.e. pip install youtube-dl or try this
> 
> The correct way to install Youtube-DL so that other Python programs can import it is to download the .tar.gz archive, then use 7-Zip (or some other unzipper that can handle .tar.gz files) to extract the inner youtube_dl folder (the one that's currently about 3MB in size) to your Python's site-packages folder, e.g. C:\Python27\Lib\site-packages. There, it will automtically be found by tumblr_backup.
> 
> If you did it right, there will be the file ...\Python27\Lib\site-packages\youtube_dl\__init__.py (plus many others, of course), and this should just work in your Python shell:

> ```
> >>> import youtube_dl
> >>> youtube_dl.YoutubeDL
> <class 'youtube_dl.YoutubeDL.YoutubeDL'>
> >>>
> 
> ```

What exactly does .tar.gz archive mean? I understand that the youtube_dl folder is what needs to be extracted and placed into \lib\site-packages but I'm completely lost as to where to find it.

Alternatively, where exactly do I type pip install youtube-dl because neither the Windows 10 command prompt nor Python.exe can run that command. The errors are listed bellow respectively:

`'pip' is not recognized as an internal or external command, operable program or batch file.`

-----

`  File "<stdin>", line 1
    pip install youtube-dl
              ^
SyntaxError: invalid syntax
```

**Comment by Cebtenzzre** [comment] 2018-12-14 22:17
Dupe of #89, this belongs as a comment on that issue.

**Closed by Cebtenzzre** 2018-12-14 22:17 UTC
