### ISSUE TITLE
properly installing youtube_dl

### ISSUE THREAD

**Issue by aldunbar** [bbolli/tumblr-utils#173] opened 2018-12-12 03:14 UTC
I installed youtube_dl using homebrew (says 2018.12.09 is installed and up-to-date), but when I run --save-video, I get the message: 
tumblr_backup.py: error: --save-video: module 'youtube_dl' is not installed
What am I doing wrong?

**Comment by aldunbar** [comment] 2018-12-12 03:45
It looks like the latter:
https://rg3.github.io/youtube-dl/
which I got to from:
https://github.com/bbolli/tumblr-utils/blob/master/tumblr_backup.md

**Comment by Hrxn** [comment] 2018-12-12 04:43
`pip2 install --upgrade youtube-dl`

**Comment by aldunbar** [comment] 2018-12-12 05:11
Despite having 2.7.10, I'm getting -bash: pip: command not found (and pip2 : command not found). 
I can run  --save-video-tumblr  and get videos (and a lot of 403 forbiddens), but still no luck on --save-video. I'll keep on muddling my way through. Thanks.

**Comment by aldunbar** [comment] 2018-12-12 05:48
Closer...
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/youtube_dl'
Consider using the `--user` option or check the permissions.

**Comment by Hrxn** [comment] 2018-12-12 11:23
Well, change permissions manually if necessary..
Or try this:
`pip2 install --upgrade --user youtube-dl`

**Comment by moonlit** [comment] 2018-12-13 06:54
`pip` may need to be run from within Python to install packages for use by `python2` instead of Python 3 on macOS if both are installed. At least on our system Python 3 is using `pip3` but Python 2 does not seem to provide the corresponding `pip` or `pip2`.

`sudo -H python2 -m pip install youtube_dl` worked for us!

**Comment by Cebtenzzre** [comment] 2018-12-14 22:18
Dupe of #89

**Closed by Cebtenzzre** 2018-12-14 22:18 UTC
