### ISSUE TITLE
Mac youtube-dl installed, still getting --save-video error

### ISSUE THREAD

**Issue by tinymoss** [bbolli/tumblr-utils#207] opened 2019-02-24 05:31 UTC
Hi! Running commit b0b8158, I'm getting an error with the option to download all videos. I'm familiar with youtube-dl and ffmpeg and use both all the time, but I keep getting an error telling me the module is not found. If someone has any insight on how I can fix this it would be greatly appreciated.  

This is a copy of what I get:

```
me:bbolli-tumblr-utils-b0b8158 me$ python tumblr_backup.py -p 2018 --save-video blogname
Usage: tumblr_backup.py [options] blog-name ...

tumblr_backup.py: error: --save-video: module 'youtube_dl' is not installed
me:bbolli-tumblr-utils-b0b8158 me$ youtube-dl --version
2019.02.18
```

**Comment by Cebtenzzre** [comment] 2019-02-24 06:21
Dupe of #89.  The program and the module are not the same thing.  Skip to the end because most of the suggested commands to install the module are either wrong or incomplete.

@bbolli Still waiting for your review of PR #185.  Once that's merged, people will stop creating issues about this :)

**Closed by Cebtenzzre** 2019-02-24 06:21 UTC

**Comment by tinymoss** [comment] 2019-02-24 06:40
Thank you so much! I noticed there was other people having this issue but those fixes seemed to be windows specific, but the last command you mention was applicable to me. 

However, I use homebrew to install/update youtube-dl, I'm weary of installing a dupe via pip because like I said I do use youtube-dl semi regularly, dose that command only affect the directory I ran it in? Or should I run something to clean up this module after I'm done to avoid any issues with youtube-dl down the line?

**Comment by Cebtenzzre** [comment] 2019-02-24 17:53
For tumblr-utils you need the python2 version of youtube-dl, whereas the python3 version of youtube-dl is usually what is distributed.  The documentation PR should probably be updated to explain that more correctly.
What I recommend is to keep the homebrew installation of youtube-dl, and use `install --user <package>` with pip to install the python2 version to your `/home` directory.  That way both versions are available, but the homebrew version has a higher priority.    If `head -1 $(which youtube-dl)` gives different output after installing youtube-dl from pip, you may want to try reordering your PATH, or simply uninstalling the homebrew version.
