### ISSUE TITLE
Backup script doesn't save highest resolution image

### ISSUE THREAD

**Issue by andrewia** [bbolli/tumblr-utils#80] opened 2016-08-06 08:00 UTC
I love the tumblr_backup.py script and it works great!  There is one flaw that I noticed: the script backs up the direct image url it is given, when it could be downloading the highest resolution copy.  For example, here is an image URL from my dashboard: `https://66.media.tumblr.com/15dbfa8bc20672834ca3bdd7d2125bf7/tumblr_mx1d850OnV1sn5axuo1_540.png`.  If you change the end of the URL to `_1280.png` you get a much higher resolution picture.  The number after the underscore specify the maximum width or height for an image.  1280 is the highest resolution supported, so changing the end of every URL to `_1280` will download the maximum resolution possible of every image.  This works for regular and inline images, but not GIFs.  Here's a poorly written function that implements this suggestion: 

```python
    # A hacky addition that changes the image url's resolution to "_1280" (the maximum)
    # If the image is a gif, then don't change it because their maximum resolutions vary
    # Yes, this code is terrible and there are a million better ways to implement it
    def fix_image_url(self, image_url):
        # Don't change image's url if domain is not tumblr
        if ".tumblr.com/" not in image_url:
            return image_url
        # Don't change image's url if filetype is gif
        if image_url[-3:] == "gif":
            return image_url
        # Search from end of URL to find period and underscore
        periodIndex = len(image_url)
        periodFound = underscoreFound = False
        while periodFound == False:
            periodIndex -= 1
            if image_url[periodIndex] == ".":
                periodFound = True
            if periodIndex == 0:
                return image_url
        underscoreIndex = periodIndex
        while underscoreFound == False:
            underscoreIndex -= 1
            if image_url[underscoreIndex] == "_":
                underscoreFound = True
            if underscoreIndex == 0:
                return image_url
        # If there are a lot of characters between the period and underscore, then there is no resolution number in the URL
        if periodIndex - underscoreIndex > 4:
            return image_url
        # Make new URL from parts of old URL
        newURL = image_url[0:underscoreIndex+1]
        newURL += "1280"
        newURL += image_url[periodIndex:]
        return newURL
```

Maybe this function can be rewritten and added to the script so everyone can enjoy high resolution backups!

**Comment by Hrxn** [comment] 2016-08-06 12:22
You sure about the GIFs? Because `*_1280.gif` seems to work for me, i.e. it's a valid URL and you get the correct result. Not that I've ever seen a GIF with this width, so it could be overkill, but you'll get the same result as with `*_540.gif`, for example. So, why not?

On the other hand, tumblr_backup gives you the image returned by the API, and it should always be the appropriate size. Not sure where your *_540.png` example comes from, but this may be caused by the dashboard viewing, I believe.
But, afaik, if you make a new image post on tumblr, and upload a file from your computer that is a digital image taken with your camera with a couple of MPixels in size, the API should return `*_1280.jpg` for the actual resource hosted on tumblr, and it should still have the original dimensions. Although Tumblr maybe transcodes each upload again, I'm not sure actually.

**Comment by andrewia** [comment] 2016-08-06 16:09
I am confident Tumblr does not return the highest resolution image possible, and I have retested that last night.  You can test it yourself by running the script on its own, then running it with my function in the program (by pasting it in and adding a line near the start of the get_image_url and get_inline_image_url  functions that takes the url, passes it to my function, and then replaces the original url with the one my function returns).  You should find that the backups have higher resolution images.

**Comment by Hrxn** [comment] 2016-08-08 10:57
Okay, will try this later on some random blogs.

**Comment by bbolli** [comment] 2016-08-08 20:38
@andrewia, do you know of a blog that shows the behavior that you describe? Instead of arguing about whether this happens or not, show us an example where it happens and we can fix it.

**Comment by bbolli** [comment] 2016-08-08 23:08
I did a few tests on my own blog, and the results are as follows:

In the JSON, there are URLs for the original size picture, plus a few alternate sizes (max. size down to 75 px). In no case was the biggest alternate size larger than the original size. Even if it were, the effective resolution would not be greater, as Tumblr would have to interpolate the missing pixels. And this is not CSI where one can just zoom in...

So I'm inclined to close this issue as "won't fix".

Any objections?

**Comment by andrewia** [comment] 2016-08-09 03:19
The behavior only seems to happen on a few blogs.  For example, murooned.tumblr.com works fine, but askarkani.tumblr.com has many images that aren't full resolution unless the URL is modified, especially inline images.

**Comment by bbolli** [comment] 2016-08-09 08:31
Oh, I see now that the issue is mainly about inline images in text posts. They are a completely different beast than photo posts. I'll do an improved version of your proposed fix.

**Comment by andrewia** [comment] 2016-08-09 21:06
Great, thanks for your attention and best of luck!

**Closed** 2016-08-09 22:22 UTC
