### ISSUE TITLE
Update to Python 3?

### ISSUE THREAD

**Issue by drmstwizard** [bbolli/tumblr-utils#102] opened 2018-08-12 11:44 UTC
Even using `2to3`, this script relies on some variables that are unsupported by Python 3, and since Tumblr is on a bender of deleting innocuous blogs at the moment, it would be nice to be able to run the script again! Thank you.

**Comment by bbolli** [comment] 2018-08-12 18:00
Duplicate of #96 which has a separate script that uses Python 3.

**Closed by bbolli** 2018-08-12 18:00 UTC
