### ISSUE TITLE
Some blog are missing.

### ISSUE THREAD

**Issue by indrakaw** [bbolli/tumblr-utils#206] opened 2019-01-22 12:07 UTC
There are exist and required to login to view them on web browser.

In my case, there are: `tetris` and `japan-spirit`.

Here the log.
```
 tumblr_backup.py -k tetris
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/tetris.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/tetris.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/tetris.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/tetris.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/tetris.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/tetris.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/tetris.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/tetris.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/tetris.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/tetris.tumblr.com/posts?reblog_info=true&api_key=8YUsKJvcJxo2MDwmWMDiXZGuMuIbeCwuQGP5ZHSEA4jBJPMnJT&limit=1
```

**Comment by indrakaw** [comment] 2019-01-26 11:58
Yes, these blog are dashboard-only. But some of dashboard-only works. There must be kind of specifics.

**Comment by Cebtenzzre** [comment] 2019-01-26 14:36
That makes this a dupe of #161.

**Closed by Cebtenzzre** 2019-01-26 14:36 UTC
