### ISSUE TITLE
urlopen error [Errno 1]

### ISSUE THREAD

**Issue by AgentGrady** [bbolli/tumblr-utils#227] opened 2021-04-24 04:20 UTC
I am having a problem, whenever I try to download a blog I get this error message urlopen error [Errno 1, I tried entering an API code and running the CMD as a administrator but nothing seems to solve it. What am I doing wrong here?

**Comment by bbolli** [comment] 2021-04-24 11:07
Can you show the command you entered and the complete output?

**Comment by AgentGrady** [comment] 2021-04-24 11:41
Certainly

C:\Windows\System32>tumblr_backup.py askemperorclaudius-blog
<urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version> getting https://api.tumblr.com/v2/blog/askemperorclaudius-blog.tumblr.com/posts?reblog_info=true&api_key=T7YMGB3yf0kSI4Aa0ktCHr7Ip1jSRNEiWo7ISKpYe9c9IecvEz&limit=1
<urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version> getting https://api.tumblr.com/v2/blog/askemperorclaudius-blog.tumblr.com/posts?reblog_info=true&api_key=T7YMGB3yf0kSI4Aa0ktCHr7Ip1jSRNEiWo7ISKpYe9c9IecvEz&limit=1
<urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version> getting https://api.tumblr.com/v2/blog/askemperorclaudius-blog.tumblr.com/posts?reblog_info=true&api_key=T7YMGB3yf0kSI4Aa0ktCHr7Ip1jSRNEiWo7ISKpYe9c9IecvEz&limit=1
<urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version> getting https://api.tumblr.com/v2/blog/askemperorclaudius-blog.tumblr.com/posts?reblog_info=true&api_key=T7YMGB3yf0kSI4Aa0ktCHr7Ip1jSRNEiWo7ISKpYe9c9IecvEz&limit=1
<urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version> getting https://api.tumblr.com/v2/blog/askemperorclaudius-blog.tumblr.com/posts?reblog_info=true&api_key=T7YMGB3yf0kSI4Aa0ktCHr7Ip1jSRNEiWo7ISKpYe9c9IecvEz&limit=1
<urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version> getting https://api.tumblr.com/v2/blog/askemperorclaudius-blog.tumblr.com/posts?reblog_info=true&api_key=T7YMGB3yf0kSI4Aa0ktCHr7Ip1jSRNEiWo7ISKpYe9c9IecvEz&limit=1
<urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version> getting https://api.tumblr.com/v2/blog/askemperorclaudius-blog.tumblr.com/posts?reblog_info=true&api_key=T7YMGB3yf0kSI4Aa0ktCHr7Ip1jSRNEiWo7ISKpYe9c9IecvEz&limit=1
<urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version> getting https://api.tumblr.com/v2/blog/askemperorclaudius-blog.tumblr.com/posts?reblog_info=true&api_key=T7YMGB3yf0kSI4Aa0ktCHr7Ip1jSRNEiWo7ISKpYe9c9IecvEz&limit=1
<urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version> getting https://api.tumblr.com/v2/blog/askemperorclaudius-blog.tumblr.com/posts?reblog_info=true&api_key=T7YMGB3yf0kSI4Aa0ktCHr7Ip1jSRNEiWo7ISKpYe9c9IecvEz&limit=1
<urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version> getting https://api.tumblr.com/v2/blog/askemperorclaudius-blog.tumblr.com/posts?reblog_info=true&api_key=T7YMGB3yf0kSI4Aa0ktCHr7Ip1jSRNEiWo7ISKpYe9c9IecvEz&limit=1

**Comment by bbolli** [comment] 2021-04-24 12:08
Please try `tumblr_backup.py -S askemperorclaudius-blog`

**Comment by AgentGrady** [comment] 2021-04-24 19:42
OK, I tried that and I get the exact same problem

**Comment by Cebtenzzre** [comment] 2021-04-24 20:14
Closing as duplicate of #226

**Closed by Cebtenzzre** 2021-04-24 20:14 UTC
Labels: duplicate

**Comment by bbolli** [comment] 2021-04-25 09:39
I'm not sure if this is a duplicate. #226 refers to macOS, not Windows.

**Comment by Cebtenzzre** [comment] 2021-04-25 16:00
@bbolli This _can_ occur on Windows if using a really old Python build (2.7.2 or older), as TLS 1.2 support was added to OpenSSL 1.0.1 released on March 14, 2012. But that isn't a tumblr-utils issue as it is trivial to update to Python 2.7.18 on Windows.

**Comment by bbolli** [comment] 2021-04-26 14:15
So, @AgentGrady, what's your Python version?
