### ISSUE TITLE
Backup hangs after 2200+ posts

### ISSUE THREAD

**Issue by sansdance** [bbolli/tumblr-utils#192] opened 2018-12-16 15:39 UTC
Since I have about 30k posts on my blog, I decided to backup incrementally (by year) to reduce waiting time. Until now it's worked fine. Whenever I try to backup this year, the program always hangs at 2200 - 2249 posts. Here's the output from my terminal:

C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a>tumblr_backup.py -p 2018 ceilingpepper

Unknown post type 'None' in post #180849021497
Unknown post type 'None' in post #180824893907
Exception in thread Thread-17:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 781, in save_content
    self.save_post()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 955, in save_post
    f.write(self.get_post())
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 910, in get_post
    typ = ('liked-' if options.likes else '') + self.typ
TypeError: cannot concatenate 'str' and 'NoneType' objects

Exception in thread Thread-14:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 781, in save_content
    self.save_post()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 955, in save_post
    f.write(self.get_post())
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 910, in get_post
    typ = ('liked-' if options.likes else '') + self.typ
TypeError: cannot concatenate 'str' and 'NoneType' objects

*[the first 2 exceptions always come up at around 150 posts]

Unknown post type 'None' in post #180638550412
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 735, in save_content
    append(post['player'][-1]['embed_code'])
KeyError: 'player'

Exception in thread Thread-16:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 781, in save_content
    self.save_post()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 955, in save_post
    f.write(self.get_post())
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 910, in get_post
    typ = ('liked-' if options.likes else '') + self.typ
TypeError: cannot concatenate 'str' and 'NoneType' objects

xception in thread Thread-15: 450 to 499 of 30498
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 735, in save_content
    append(post['player'][-1]['embed_code'])
KeyError: 'player'

Unknown post type 'None' in post #180472022137
Exception in thread Thread-13:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 781, in save_content
    self.save_post()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 955, in save_post
    f.write(self.get_post())
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 910, in get_post
    typ = ('liked-' if options.likes else '') + self.typ
TypeError: cannot concatenate 'str' and 'NoneType' objects

Unknown post type 'None' in post #180348335772
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 781, in save_content
    self.save_post()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 955, in save_post
    f.write(self.get_post())
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 910, in get_post
    typ = ('liked-' if options.likes else '') + self.typ
TypeError: cannot concatenate 'str' and 'NoneType' objects

Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 735, in save_content
    append(post['player'][-1]['embed_code'])
KeyError: 'player'

Exception in thread Thread-8:650 to 699 of 30498
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 735, in save_content
    append(post['player'][-1]['embed_code'])
KeyError: 'player'

Exception in thread Thread-12:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 735, in save_content
    append(post['player'][-1]['embed_code'])
KeyError: 'player'

Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 735, in save_content
    append(post['player'][-1]['embed_code'])
KeyError: 'player'

Unknown post type 'None' in post #180063676072
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 781, in save_content
    self.save_post()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 955, in save_post
    f.write(self.get_post())
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 910, in get_post
    typ = ('liked-' if options.likes else '') + self.typ
TypeError: cannot concatenate 'str' and 'NoneType' objects

Exception in thread Thread-19:50 to 899 of 30498
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 735, in save_content
    append(post['player'][-1]['embed_code'])
KeyError: 'player'

Unknown post type 'None' in post #179979969437
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 781, in save_content
    self.save_post()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 955, in save_post
    f.write(self.get_post())
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 910, in get_post
    typ = ('liked-' if options.likes else '') + self.typ
TypeError: cannot concatenate 'str' and 'NoneType' objects

Exception in thread Thread-18:00 to 949 of 30498
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 735, in save_content
    append(post['player'][-1]['embed_code'])
KeyError: 'player'

Ecxception in thread Thread-11:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 735, in save_content
    append(post['player'][-1]['embed_code'])
KeyError: 'player'
eilingpepper:
Exception in thread Thread-9:0498
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 735, in save_content
    append(post['player'][-1]['embed_code'])
KeyError: 'player'

Unknown post type 'None' in post #179708999777
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 781, in save_content
    self.save_post()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 955, in save_post
    f.write(self.get_post())
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 910, in get_post
    typ = ('liked-' if options.likes else '') + self.typ
TypeError: cannot concatenate 'str' and 'NoneType' objects

Exception in thread Thread-20:050 to 1099 of 30498
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 735, in save_content
    append(post['player'][-1]['embed_code'])
KeyError: 'player'

HTTP Error 404: Not Found downloading https://dl.dropboxusercontent.com/u/26985647/mrsb.png
Exception in thread Thread-6:1250 to 1299 of 30498
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 1043, in handler
    work()
  File "C:\bbolli-tumblr-utils-30e140a\bbolli-tumblr-utils-30e140a\tumblr_backup.py", line 735, in save_content
    append(post['player'][-1]['embed_code'])
KeyError: 'player'

ceilingpepper: Getting posts 2200 to 2249 of 30498

**Comment by sansdance** [comment] 2018-12-16 15:47
Quick addition: I have posts from October-December saved from an early attempt to backup, which was abandoned due to a turbulent internet connection + not yet knowing about the credentials you could add to make backup easier (heh)

**Comment by Cebtenzzre** [comment] 2018-12-16 16:38
Dupe of #179, I think

**Closed** 2018-12-16 16:39 UTC
Labels: duplicate
